export enum CargoEmpleado {
    // Alta Gerencia
    GENERAL_MANAGER = "GERENTE GENERAL",
    HOTEL_MANAGER = "GERENTE DE OPERACIONES",
    ADMINISTRATIVE_ASSISTANT = "ASISTENTE ADMINISTRATIVO",

    // Recepción y Servicio al Huésped
    FRONT_DESK_MANAGER = "JEFE DE RECEPCION",
    RECEPCIONIST = "RECEPCIONISTA",
    CONCIERGE = "CONSERJE",
    BELLBOY = "BOTONES",
    NIGHT_AUDITOR = "AUDITOR NOCTURNO",

    // Ama de Llaves y Limpieza
    HOUSEKEEPING_MANAGER = "JEFE DE LIMPIEZA",
    ROOM_ATTENDANT = "CAMARERO DE PISO",
    LAUNDRY_STAFF = "PERSONAL DE LAVANDERIA",
    CLEANER = "PERSONAL DE LIMPIEZA GENERAL",

    // Alimentos y Bebidas
    FB_MANAGER = "GERENTE DE ALIMENTOS Y BEBIDAS",
    CHEF = "CHEF EJECUTIVO",
    KITCHEN_PORTER = "AYUDANTE DE COCINA",
    WAITER = "MESERO",
    BARTENDER = "BARMAN",

    // Mantenimiento y Seguridad
    MAINTENANCE_MANAGER = "JEFE DE MANTENIMIENTO",
    TECHNICIAN = "TECNICO DE MANTENIMIENTO",
    SECURITY_GUARD = "GUARDIA DE SEGURIDAD",

    // Ventas y Marketing
    SALES_MANAGER = "GERENTE DE VENTAS",
    REVENUE_MANAGER = "GERENTE DE REVENUE"
}
